album: The Legend of Zelda | A Link to the Past | GBA | Gamerip Tracks

name_prefix: The Legend of Zelda - A Link to the Past OST

videos:
  - "01 Title A ~ Link to the Past"
  - "02 Title B ~ Link to the Past"
  - "03 Beginning of the Journey"
  - "04 Seal of Seven Maidens"
  - "05 Time of the Falling Rain"
  - "06 Majestic Castle"
  - "07 Princess Zelda's Rescue"
  - "08 Safety in the Sanctuary"
  - "09 Hyrule Field Main Theme"
  - "10 Kakariko Village"
  - "11 Guessing-Game House"
  - "12 Fortune Teller"
  - "13 Soldiers of Kakariko Village"
  - "14 Dank Dungeons"
  - "15 Lost Ancient Ruins"
  - "16 Anger of the Guardians"
  - "17 Great Victory!"
  - "18 The Silly Pink Rabbit!"
  - "19 Forest of Mystery"
  - "20 Unsealing the Master Sword"
  - "21 Priest of the Dark Order"
  - "22 Dark Golden Land"
  - "23 Black Mist"
  - "24 Dungeon of Shadows"
  - "25 Meeting the Maidens"
  - "26 The Goddess Appears"
  - "27 Release of Ganon"
  - "28 Ganon's Message"
  - "29 The Prince of Darkness"
  - "30 Power of the Gods"
  - "31 Epilogue ~ Beautiful Hyrule"
  - "32 Staff Roll"
  - "The Legend of Zelda | A Link to the Past | GBA | Gamerip Tracks"

description: |
  🎮 THE LEGEND OF ZELDA | 1986

  📀 Nazo no Murasamejo / The Legend of Zelda: The Hyrule Fantasy OST - Orchestra Version | https://www.youtube.com/playlist?list=PL90QAKwVH1t5TmnkCitcq-q6c7N7zpzc5
  📀 The Hyrule Fantasy: The Legend of Zelda / Nazo no Murasamejo | https://www.youtube.com/playlist?list=PL90QAKwVH1t5cjyZDh-XFGi97FnyJjHPt
  📀 The Legend of Zelda: Gamerip Tracks | https://www.youtube.com/playlist?list=PL90QAKwVH1t7oEVacVzp0MeSEj9vSBow7
  📀 The Legend of Zelda Complete OST | https://www.youtube.com/playlist?list=PL90QAKwVH1t4oohxP4-sZ6FysLvvWPOKR

  🎮 ZELDA II: THE ADVENTURE OF LINK | 1987

  📀 Zelda II: The Adventure of Link | FDS | Gamerip Tracks | https://www.youtube.com/playlist?list=PL90QAKwVH1t5IVOLKJ6ItZORPsk1P-06A
  📀 Zelda II: The Adventure of Link | NES | Gamerip Tracks | https://www.youtube.com/playlist?list=PL90QAKwVH1t6w7E9dGjr2GWbqj32zRn1t
  📀 Zelda II: The Adventure of Link Complete OST | https://www.youtube.com/playlist?list=PL90QAKwVH1t7jJSQTiNfXoBbG6hj21PIn

  🎮 THE LEGEND OF ZELDA: A LINK TO THE PAST | 1991

  📀 The Legend of Zelda: A Link to the Past - SNES - Gamerip Tracks | https://www.youtube.com/playlist?list=PL90QAKwVH1t6XNpVAkHvQu9_flww3drYa
  📀 The Legend of Zelda: A Link to the Past - GBA - Gamerip Tracks | https://www.youtube.com/playlist?list=PLJhWe-nKD2Vk
  📀 The Legend of Zelda: A Link to the Past Complete OST | https://www.youtube.com/playlist?list=PL90QAKwVH1t77ou014gVjbIRxt-b35jSJ

thumbnail: "D:/@Seyfer/Proyectos/@YouTube/OST/02 In Progress/The Legend of Zelda/03 The Legend of Zelda - A Link to the Past - 1991/02 GBA - Gamerip Tracks/images/miniatura3.png"

playlists:
  - PLJhWe-nKD2Vk # The Legend of Zelda: A Link to the Past - GBA - Gamerip Tracks
  - PL90QAKwVH1t77ou014gVjbIRxt-b35jSJ # The Legend of Zelda: A Link to the Past Complete OST

made_for_kids: false
contains_synthetic_media: false

tags:
  - tags # Doesn't matter

game: game # not used

publication:
  # Fecha en formato ISO 8601: YYYY-MM-DDTHH:MM:SS
  first_publish_at: "2026-10-08T22:00:00"
  timezone: "Europe/Paris"
  interval_days: 1
